### ISSUE TITLE
 Issue 6 for Milestone 3: Training the Model (Lab 5-8)

### ISSUE THREAD

**Issue by Ayan-code571** [Ayan-code571/BI-Project#6]
- [ ] Data splitting
- [ ] Bootstrapping
- [ ] Cross validation (basic, repeated, or LOOCV)
- [ ] Model training for either classification, regression, association, or clustering (as applicable)
- [ ] Model performance comparison using resamples (for classification and regression)
